/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AdministrativeRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jayal
 */
public class ManageSOCUsersJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
    OrganizationDirectory orgdir;
    EcoSystem system;

    /**
     * Creates new form ManageSOCUsersJPanel
     */
    public ManageSOCUsersJPanel(JPanel userProcessContainer,OrganizationDirectory orgdir, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.orgdir=orgdir;
        this.system=system;
         popOrganizationComboBox();
        popData();
        
        
        
    }
void popOrganizationComboBox()
{
manageUserOrganizationJCombo.removeAllItems();
for (Organization organization : orgdir.getOrganizationList()) {
            manageUserOrganizationJCombo.addItem(organization);
        }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        manageUserJTable = new javax.swing.JTable();
        manageUserOrganizationJCombo = new javax.swing.JComboBox();
        manageUserRoleJCombo = new javax.swing.JComboBox();
        manageuserEmployeeJCombo = new javax.swing.JComboBox();
        manageuserNameJText = new javax.swing.JTextField();
        managepasswordJText = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        manageUserJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageUserJTable);
        if (manageUserJTable.getColumnModel().getColumnCount() > 0) {
            manageUserJTable.getColumnModel().getColumn(0).setResizable(false);
            manageUserJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(74, 32, 371, 219);

        manageUserOrganizationJCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        manageUserOrganizationJCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserOrganizationJComboActionPerformed(evt);
            }
        });
        add(manageUserOrganizationJCombo);
        manageUserOrganizationJCombo.setBounds(154, 310, 85, 20);

        manageUserRoleJCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(manageUserRoleJCombo);
        manageUserRoleJCombo.setBounds(530, 310, 93, 20);

        manageuserEmployeeJCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(manageuserEmployeeJCombo);
        manageuserEmployeeJCombo.setBounds(366, 310, 77, 20);
        add(manageuserNameJText);
        manageuserNameJText.setBounds(154, 359, 85, 20);
        add(managepasswordJText);
        managepasswordJText.setBounds(366, 359, 77, 20);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(366, 417, 57, 23);

        jLabel1.setText("Organization");
        add(jLabel1);
        jLabel1.setBounds(74, 313, 61, 14);

        jLabel2.setText("Employee");
        add(jLabel2);
        jLabel2.setBounds(293, 313, 46, 14);

        jLabel3.setText("Role");
        add(jLabel3);
        jLabel3.setBounds(493, 313, 21, 14);

        jLabel4.setText("Username");
        add(jLabel4);
        jLabel4.setBounds(80, 360, 60, 14);

        jLabel5.setText("Password");
        add(jLabel5);
        jLabel5.setBounds(290, 360, 50, 14);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(550, 30, 83, 61);
    }// </editor-fold>//GEN-END:initComponents

    private void manageUserOrganizationJComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserOrganizationJComboActionPerformed
        // TODO add your handling code here:
        
        Organization organization = (Organization) manageUserOrganizationJCombo.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
        }  
    }//GEN-LAST:event_manageUserOrganizationJComboActionPerformed
void popData()
{
DefaultTableModel model = (DefaultTableModel) manageUserJTable.getModel();

        model.setRowCount(0);

        for (Organization organization : orgdir.getOrganizationList()) {
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) manageUserJTable.getModel()).addRow(row);
            }
        }



}
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String userName = manageuserNameJText.getText();
        String password = managepasswordJText.getText();
        
        
        if(manageuserNameJText.getText().equals("")||managepasswordJText.getText().equals(""))
        {
        JOptionPane.showMessageDialog(null, "Please enter all the fields");
        return;
        
        }
            if(!system.checkIfUsernameIsUnique(userName))
   {
   JOptionPane.showMessageDialog(null, "User Name is not unique");
   return;
   
   }
        
        
        
        Organization organization = (Organization) manageUserOrganizationJCombo.getSelectedItem();
        Employee employee = (Employee) manageuserEmployeeJCombo.getSelectedItem();
        Role role = (Role) manageUserRoleJCombo.getSelectedItem();
        
        organization.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
       // organization.getUserAccountDirectory().getUserAccountList().add(ac); 
        popData();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed
void populateEmployeeComboBox(Organization organization)
{
  manageuserEmployeeJCombo.removeAllItems();
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            manageuserEmployeeJCombo.addItem(employee);
        }  
    
    
}

void populateRoleComboBox(Organization organization)
{
manageUserRoleJCombo.removeAllItems();
        for (Role role : organization.getSupportedRole()){
           
            
            
            
                       manageUserRoleJCombo.addItem(role);
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manageUserJTable;
    private javax.swing.JComboBox manageUserOrganizationJCombo;
    private javax.swing.JComboBox manageUserRoleJCombo;
    private javax.swing.JTextField managepasswordJText;
    private javax.swing.JComboBox manageuserEmployeeJCombo;
    private javax.swing.JTextField manageuserNameJText;
    // End of variables declaration//GEN-END:variables
}
