/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.BankEmployeeRole;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.TransferFundWorkRequest;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jayal
 */
public class ProcessTransferRequestJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
    TransferFundWorkRequest request;
    UserAccount sender;
    
    /**
     * Creates new form ProcessTransferRequestJPanel
     */
    public ProcessTransferRequestJPanel(JPanel userProcessContainer,TransferFundWorkRequest request, UserAccount ua) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
      this.sender=ua;
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        actionJComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Action to be Taken");

        actionJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fund Transfer Approved", "Disapprove(Requested amount exceeds permissable limit)", "Insuficient Balance in Account" }));
        actionJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionJComboBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Submit Result");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(84, 84, 84)
                        .addComponent(actionJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(actionJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        request.setMessage(String.valueOf(actionJComboBox.getSelectedItem()));
        
        request.setStatus("Completed");
        String s= (String)actionJComboBox.getSelectedItem();
        if(s.equalsIgnoreCase("approved"));
        
        
        
        {
        
            JOptionPane.showMessageDialog(null, "Approved");
        
        final String username = "banknu0";
		final String password = "Lekhrajani90!";

		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");

		Session session = Session.getInstance(props,
		  new javax.mail.Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(username, password);
			}
		  });
                
                
                try {

			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress("banknu0@gmail.com"));
			message.setRecipients(Message.RecipientType.TO,
				InternetAddress.parse("7326667221@cingularme.com "));
			message.setSubject("Fund Transfer Request approved.");
			message.setText("Dear ,"+"  " +sender.getPerson().getName()+
				"Funds have been transferred");

			Transport.send(message);

			System.out.println("Done");

		} catch (MessagingException e) {
			throw new RuntimeException(e);
		}
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        }
        
        if(s.equalsIgnoreCase("disapprove"))
            
            
        {
        JOptionPane.showMessageDialog(null, "Disapproved");
        
        final String username = "banknu0";
		final String password = "Lekhrajani90!";

		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");

		Session session = Session.getInstance(props,
		  new javax.mail.Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(username, password);
			}
		  });
                
                
                try {

			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress("banknu0@gmail.com"));
			message.setRecipients(Message.RecipientType.TO,
				InternetAddress.parse("7326667221@cingularme.com "));
			message.setSubject("Fund Transfer Request Rejected.");
			message.setText("Dear ,"+"  " +sender.getPerson().getName()
				+ "Rejected due to insufficient bal");

			Transport.send(message);

			System.out.println("Done");

		} catch (MessagingException e) {
			throw new RuntimeException(e);
		}
        
        
        
        
        
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void actionJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox actionJComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
