/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CustomerRole;

import Business.Customer.Customer;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SuspiciousActivityRequest;
import javax.swing.JOptionPane;

/**
 *
 * @author jayal
 */
public class customerSecurtityJFrame extends javax.swing.JFrame {

    
    Customer c;
    String userName;
    String password;
    Enterprise inEnterprise;
    EcoSystem system;
    DB4OUtil dB4OUtil;
    UserAccount userAccount;
    
    /**
     * Creates new form customerSecurtityJFrame
     */
    public customerSecurtityJFrame(Customer c, String userName, String password, Enterprise inEnterprise, EcoSystem system, DB4OUtil dB4OUtil,UserAccount userAccount) {
        initComponents();
        
        this.c=c;
        this.userName=userName;
        this.password=password;
        this.userAccount=userAccount;
        
        this.inEnterprise=inEnterprise;
        this.system=system;
        this.dB4OUtil=dB4OUtil;
        securtityquestionlabel.setText(c.getSecurityQuestion());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        securtityquestionlabel = new javax.swing.JLabel();
        securityAnswer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 271, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Answer Security Question");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 46, -1, -1));

        securtityquestionlabel.setText("securityquestionlabel");
        getContentPane().add(securtityquestionlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 126, -1, -1));
        getContentPane().add(securityAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 186, 148, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(securityAnswer.getText().equals(""))
        {
        
            JOptionPane.showMessageDialog(null, "Please answer the security question");
            return;
        
        }
        
        
   
        
        
      if(securityAnswer.getText().equalsIgnoreCase(c.getSecurityanswer()))  
          
      {
      customerJFrame cus=new customerJFrame((Customer)userAccount.getPerson(), userName, password, inEnterprise, system, dB4OUtil,userAccount);
           this.dispose();
           cus.setVisible(true);
           return;
      
      
      
      }
      
      
        if(!securityAnswer.getText().equalsIgnoreCase(c.getSecurityanswer()))  
          
      {
          
          system.numberofsuspiciousevents++;
   JOptionPane.showMessageDialog(null, "You have not answered security question correctly. In case you have forgotten, contact Service Desk");
      
     return; 
      
      }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerSecurtityJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerSecurtityJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerSecurtityJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerSecurtityJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new customerSecurtityJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField securityAnswer;
    private javax.swing.JLabel securtityquestionlabel;
    // End of variables declaration//GEN-END:variables
}
