/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.IncidentManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.IMTeamOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SuspiciousActivityRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jaya_L
 */
public class IncidentManagerWorkArea extends javax.swing.JPanel {
private JPanel userProcessContainer;
private IMTeamOrganization organization;
private Enterprise enterprise;
private UserAccount userAccount;
EcoSystem system;
    /**
     * Creates new form IncidentManagerWorkArea
     */
    public IncidentManagerWorkArea(JPanel userProcessContainer, UserAccount account, IMTeamOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=account;
        this.enterprise=enterprise;
        this.organization=organization;
        this.system=system;
        populateTable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    void populateTable()
    {
    
    DefaultTableModel model = (DefaultTableModel)SuspiciousActivityJTable.getModel();
model.setRowCount(0);
for(WorkRequest request : organization.getWorkQueue().getWorkRequestList())
{
if(request instanceof SuspiciousActivityRequest){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getSender().getPerson().getName();
            //=(Customer)request.getSender().getPerson();
            
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getPerson().getName();
            row[3] = request.getStatus();
            row[4]=((SuspiciousActivityRequest) request).getCriticallevel();
            
            model.addRow(row);
    
    }
}
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SuspiciousActivityJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        messageFieldJText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setText("My Work Area");
        add(jLabel1);
        jLabel1.setBounds(20, 30, 68, 14);

        SuspiciousActivityJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Incident", "Sender", "Receiver", "Status", "Criticality"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(SuspiciousActivityJTable);
        if (SuspiciousActivityJTable.getColumnModel().getColumnCount() > 0) {
            SuspiciousActivityJTable.getColumnModel().getColumn(0).setResizable(false);
            SuspiciousActivityJTable.getColumnModel().getColumn(1).setResizable(false);
            SuspiciousActivityJTable.getColumnModel().getColumn(2).setResizable(false);
            SuspiciousActivityJTable.getColumnModel().getColumn(3).setResizable(false);
            SuspiciousActivityJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(130, 22, 403, 261);

        jLabel3.setText("Message");
        add(jLabel3);
        jLabel3.setBounds(164, 304, 42, 14);

        jButton1.setText("Resolve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(260, 339, 71, 23);
        add(messageFieldJText);
        messageFieldJText.setBounds(260, 301, 180, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Alert-Icon.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(590, 54, 50, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        // TODO add your handling code here:
        
        int selectedRow = SuspiciousActivityJTable.getSelectedRow();
       if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a request");
            return;
        }
       
          
       
       SuspiciousActivityRequest request1 = (SuspiciousActivityRequest)SuspiciousActivityJTable.getValueAt(selectedRow, 0);

    
    
       
       
       
       if(messageFieldJText.getText().equals(""))
      {
      
          JOptionPane.showMessageDialog(this, "Please enter the message");
          return;
      
      
      }
        
        
             request1.setStatus("Completed");
             request1.setMessage(messageFieldJText.getText());
             populateTable();
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SuspiciousActivityJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messageFieldJText;
    // End of variables declaration//GEN-END:variables
}
