/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ReportingRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.IMTeamOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SuspiciousActivityRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jayal
 */
public class WorkOnitJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;

        SuspiciousActivityRequest request; 
        UserAccount ua;
        Enterprise e;
        Organization organization; 
        EcoSystem system;
    /**
     * Creates new form WorkOnitJPanel
     */
    public WorkOnitJPanel(JPanel userProcessContainer,SuspiciousActivityRequest request, UserAccount ua, Enterprise e, Organization organization, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
        this.ua=ua;
        this.e=e;
        this.organization=organization;
        this.system=system;
        critical.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messagetobeSenttoIMJTextfield = new javax.swing.JTextField();
        severityComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        critical = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        severityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Critical", "High", "Medium", " " }));
        severityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                severityComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Message");

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        critical.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        critical.setForeground(new java.awt.Color(255, 0, 0));
        critical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/critical.png"))); // NOI18N
        critical.setText("Assign it to IM Team");

        jLabel2.setText("Assign Severity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(severityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(critical))
                            .addComponent(messagetobeSenttoIMJTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(severityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(critical)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messagetobeSenttoIMJTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(57, 57, 57)
                .addComponent(jButton2)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String s=(String) severityComboBox.getSelectedItem();
        if(messagetobeSenttoIMJTextfield.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter the message");
            return;
            
        
        
        }
        if(s.equalsIgnoreCase("high"))
        {
        
        request.setStatus("Completed");
        system.opentickets--;
        system.closedTickets++;
        system.hightickets++;
        
        return;
        
        }
        
        
        if(s.equalsIgnoreCase("medium"))
        {
        
        request.setStatus("Completed");
        system.opentickets--;
        system.closedTickets++;
        system.mediumtickets++;
        
        return;
        
        }
        
        
       
        if(s.equalsIgnoreCase("critical"))
        {
        system.criticaltickets++;
        critical.setVisible(true);
        System.out.print(system.criticaltickets);
        request.setMessage("Sending it to IM for further investigation");
        
        Organization imorg=null;
        for(Network n:system.getNetworkList())
            
        {
        
        for(Enterprise e:n.getEnterpriseDirectory().getEnterpriseList())
        {
        
        for(Organization o:e.getOrganizationDirectory().getOrganizationList())
        {
        
        if(o instanceof IMTeamOrganization) // to escalate it to IM Organization
        {
        
        imorg=o; 
        break;
        
        
        }
        if(imorg!=null)
            break;
        
        }
        
        
        
        if(imorg!=null)
            break;
        
        
        }
        
        
        
        
        
        
        }
        
        if(imorg!=null)
        {
     
            imorg.getWorkQueue().getWorkRequestList().add(request); 
            request.setCriticallevel(s);
        
        
        
        }  
            
            
        
        
        
        
      
//return;
        
        
        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void severityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_severityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_severityComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel critical;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField messagetobeSenttoIMJTextfield;
    private javax.swing.JComboBox severityComboBox;
    // End of variables declaration//GEN-END:variables
}
