/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import Business.Customer.Customer;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PasswordResetRequest;
import javax.swing.JOptionPane;

/**
 *
 * @author jayal
 */
public class PasswordChangeRequestJFRame extends javax.swing.JFrame {

    
    UserAccount uac;
    EcoSystem system;
    DB4OUtil dboutil;
    UserAccount foundua=null;
    Customer c=null;
    Enterprise inEnterprise=null;
    Enterprise reqEnterprise=null;
    
    /**
     * Creates new form PasswordChangeRequestJFRame
     */
    public PasswordChangeRequestJFRame(EcoSystem system,DB4OUtil dboutil) {
        initComponents();
        this.system=system;
        this.dboutil=dboutil;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        otpJTextField = new javax.swing.JTextField();
        securityAnswer = new javax.swing.JTextField();
        btnPasswordReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        emailJTextField = new javax.swing.JTextField();
        securitQuestionJTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jLabel4.setText("OTP");

        btnPasswordReset.setText("Password Reset");
        btnPasswordReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordResetActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("EmailID");

        jLabel3.setText("Security Question");

        nameJTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameJTextFieldMouseEntered(evt);
            }
        });
        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });

        securitQuestionJTextField.setEditable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Security Question");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(otpJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(securityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                .addComponent(nameJTextField))
                            .addComponent(securitQuestionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(btnPasswordReset)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securitQuestionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(securityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(otpJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btnPasswordReset)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPasswordResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordResetActionPerformed
        // TODO add your handling code here:
        String name=nameJTextField.getText();
        String emailID=emailJTextField.getText();
        

        if(securityAnswer.getText()=="")
        {
            JOptionPane.showMessageDialog(null, "Please enter Security Answer");
            return;

        }
        
        for(Network n:system.getNetworkList())
        {
            for(Enterprise ent:n.getEnterpriseDirectory().getEnterpriseList())
            {

                for(UserAccount ua:ent.getUserAccountDirectory().getUserAccountList())
                {

                    if(ua.getUsername().equals(nameJTextField.getText()))

                    {
                        
                        if(ua.getPerson() instanceof Customer)
                        {
                            c=(Customer)ua.getPerson();
                        foundua=ua;
                        inEnterprise=ent;
                        break;
                        }
                        
                        
                        
                      //  ua.setFlag(false);
                        //ua.setPassword(otpJTextField.getText());
                        //securitQuestionJTextField.setText(c.getSecurityQuestion());
                    }
  
                        if(foundua!=null)
                            break;
                }
  
                        if(foundua!=null)
                            break;
            }

        }    // TODO add your handling code here:
        

        if(securityAnswer.getText().equals(c.getSecurityanswer())&&emailJTextField.getText().equals(c.getEmailAddress()) )
        {
            //foundua.setPassword(otpJTextField.getText());
            //foundua.setFlag(false);
            
            
            String message="Requested for password reset";
            PasswordResetRequest request=new PasswordResetRequest();
            request.setMessage(message);
            request.setSender(foundua);
        request.setStatus("Sent");
            
        
       for(Network n:system.getNetworkList()) 

       {
       for (Enterprise enterprise : n.getEnterpriseDirectory().getEnterpriseList())
       {
       
       if(enterprise.getNetworkname().equals(inEnterprise.getNetworkname())&& (enterprise.getEnterpriseType()!=inEnterprise.getEnterpriseType()))
           
       {
       
       
       reqEnterprise=enterprise;
       break;
       
       }
       
       if(reqEnterprise!=null)
           break;
       
       }
       
       
       
       
       }


       
       
       if(reqEnterprise!=null)
           
           
       {
       
       reqEnterprise.getWorkQueue().getWorkRequestList().add(request);
       foundua.getWorkQueue().getWorkRequestList().add(request);
       
       
       }
           
        }
        
        

    }//GEN-LAST:event_btnPasswordResetActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       // counter=0;
        dboutil.storeSystem(system);

        //container.removeAll();
        //MainJFrame mf=new MainJFrame();
        this.dispose();
        System.exit(0);

        //mf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed

        
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    private void nameJTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameJTextFieldMouseEntered
        // TODO add your handling code here:
        
        for(Network n:system.getNetworkList())
        {
            for(Enterprise ent:n.getEnterpriseDirectory().getEnterpriseList())
            {

                for(UserAccount ua:ent.getUserAccountDirectory().getUserAccountList())
                {

                    if(ua.getUsername().equals(nameJTextField.getText()))

                    {
                        c=(Customer)ua.getPerson();
                        
                        securitQuestionJTextField.setText(c.getSecurityQuestion());
                    }

                }

            }

        }    // TODO add your handling code here:
        
    }//GEN-LAST:event_nameJTextFieldMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordChangeRequestJFRame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordChangeRequestJFRame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordChangeRequestJFRame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordChangeRequestJFRame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PasswordChangeRequestJFRame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPasswordReset;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField otpJTextField;
    private javax.swing.JTextField securitQuestionJTextField;
    private javax.swing.JTextField securityAnswer;
    // End of variables declaration//GEN-END:variables
}
